### PR TITLE
Restore releng for org.eclipse.mylyn.reviews #3

### PR DESCRIPTION
**Pull request by ruspl-afed**
Add Jenkins manifest
make root pom.xml self-sufficient
fix target

### CODE REVIEW

**Comment by ruspl-afed** [comment]
Blocked by https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2437

**Comment by ruspl-afed** [comment]
Many days of fighting with pipeline and tests are over, the victims are [here](https://github.com/eclipse-mylyn/org.eclipse.mylyn.reviews/issues/5). Merging.

**Comment by wimjongman** [comment]
> Many days of fighting with pipeline and tests are over, the victims are [here](https://github.com/eclipse-mylyn/org.eclipse.mylyn.reviews/issues/5). Merging.

I feel your pain. Thank you for your time, Alexander! You guys are on a roll. Please assign discrete tasks to me. I have some breathing room over the holidays.

**Comment by ruspl-afed** [comment]
@wimjongman  It would be great if you can arrange the repository merge

**Comment by wimjongman** [comment]
Ok, sure. Let me do this.

**Pull request merged**
